# network architecture
# encoder related
elayers: 4
eunits: 512
# decoder related
dlayers: 4
dunits: 512
# attention related
adim: 256
aheads: 4

# hybrid CTC/attention
mtlalpha: 0.0

# label smoothing
lsm-weight: 0.0

# minibatch related
batch-size: 250
maxlen-in: 512  # if input length  > maxlen-in, batchsize is automatically reduced
maxlen-out: 512 # if output length > maxlen-out, batchsize is automatically reduced

# optimization related
sortagrad: 0 # Feed samples from shortest to longest ; -1: enabled for all epochs, 0: disabled, other: enabled for 'other' epochs
opt: noam
accum-grad: 4
grad-clip: 5
patience: 0
epochs: 50
dropout-rate: 0.1

# transformer specific setting
backend: pytorch
model-module: "espnet.nets.pytorch_backend.e2e_asr_transformer:E2E"
transformer-input-layer: linear     # encoder architecture type
transformer-lr: 2.0
transformer-warmup-steps: 20000
transformer-attn-dropout-rate: 0.1
transformer-length-normalized-loss: false
transformer-init: pytorch
transformer-monotonic-local-attention: 1
